export const truthTask = [
  "Kdy jsi naposledy plakal(a) a proč?",
  "Co je tvůj největší strach?",
  "Kdybys mohl(a) zůstat naživu v jakémkoliv věku navždy, který by to byl?",
  "Kdybys mohl(a) mít jakoukoliv super schopnost, kterou by to byla?",
  "Jaký byl tvůj nejhorší první rande?",
  "Máš nějaké tajné přání?",
  "Jaká byla tvá největší trapná situace?",
  "Kdybys měl(a) utrácet něčí peníze, kdo by to byl a proč?",
  "Jaká byla tvá největší láska?",
  "Jaká byla tvá největší zklamání?",
  "Kdybys mohl(a) udělat jednu věc jinak v minulosti, co by to bylo?",
  "Co je tvůj největší tajemství?",
  "Kdybys měl(a) být opačného pohlaví na jeden den, co bys dělal(a)?",
  "Kdybys měl(a) zůstat uvězněný(a) na opuštěném ostrově se třemi lidmi, kdo by to byli?",
  "Kdybys měl(a) jet na svou poslední cestu, kam bys jel(a)?",
  "Kdybys mohl(a) zpívat nebo hrát na jakýkoliv hudební nástroj, který by to byl?",
  "Kdybys měl(a) utratit velkou sumu peněz, co bys si koupil(a)?",
  "Jaký je tvůj největší neúspěch a co jsi z toho naučil(a)?",
  "Kdybys mohl(a) být jakoukoliv postavou z filmu nebo knihy, kdo by to byl?",
  "Kdybys měl(a) odejít ze svého domova a žít jinde, kde bys žil(a)?",
];

export const dareTask = [
  "Zazpívej píseň na povel ostatních hráčů",
  "Vyzkoušej si nějaký nový účes, který ti ostatní hráči navrhnou",
  "Vyzkoušej si nějaké nové jídlo, které ti ostatní hráči připraví",
  "Napiš SMS nebo zprávu někomu z tvého seznamu kontaktů, ve které mu/jí řekneš, jak moc ho/jí máš rád(a)",
  "Vyfoť se s něčím divným nebo trapným na veřejnosti a pošli fotku ostatním hráčům",
  "Zavolej někomu a zeptej se ho/jí na rande",
  "Přeřaď se s někým z hráčů, dokud se ostatní neuvolní",
  "Vezmi si kouli z žvýkačky a polož ji na čelo, aniž by sis ji dál přidržoval(a)",
  "Nasaď si oční masku a zkuste vybrat správnou potravinu z 3 různých ochutnávek",
  "Zahraj si nějakou hru na mobilu bez přestávky po dobu 5 minut",
  "Předveď nějaký taneční krok, který ti ostatní hráči naordinovali",
  "Pusť si hlasitou hudbu a zazpívej si jí na balkóně nebo venku na ulici",
  "Vyprávěj srandovní vtipy alespoň 5 minut",
  "Pojď si s někým zahrát karty nebo nějakou deskovou hru",
  "Vypi vodu nebo jiný nápoj na ex",
  "Vyfotografuj se s neznámým člověkem a pošli fotku ostatním hráčům",
  "Obleč si oblečení naruby a takhle zůstaň alespoň další hodinu",
  "Pojď si zahrát nějakou sportovní hru nebo posilovat",
  "Pojď si s někým zahrát nějakou deskovou hru nebo puzzle",
  "Zkus napsat básničku na určité téma, které ti ostatní hráči určí",
];
